name: Deploy to GitHub Pages

on:
  push:
    branches: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build-essential
        run: sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config

      - name: Install dependencies
        run: make init

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
          make build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: './projects/web/dist/'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
